- hosts: localhost
  # Add pre_task stuff to upgrade things like brew/etc
  vars:
    go_version: '1.20.5'
    rust_version: '1.62.1'
  pre_tasks:
   - name: Update and upgrade apt packages
     become: yes
     apt:
       upgrade: yes
       update_cache: yes
       force_apt_get: yes
       cache_valid_time: 86400 #One day
     when: ansible_distribution == "Ubuntu"
     tags:
       - ubuntu
       - neovim
       - devTools
  tasks:
    # TODO: Should have something in beginning for curl and brew installation
   - import_tasks: tasks/window_management.yml
   - import_tasks: tasks/general_apps.yml
   - import_tasks: tasks/terminal.yml
   - import_tasks: tasks/golang.yml
   - import_tasks: tasks/rust.yml
   - import_tasks: tasks/developer_tools.yml
   - import_tasks: tasks/neovim.yml
   - import_tasks: tasks/dotfiles.yml
   - import_tasks: tasks/dagger.yml
   - import_tasks: tasks/gitconfig.yml
   - import_tasks: tasks/lsp.yml
