- name: Check dagger installed
  ansible.builtin.shell: type dagger
  register: check_dagger
  ignore_errors: true
  tags:
    - dagger
- name: Install dagger linux
  ansible.builtin.shell: curl -L https://dl.dagger.io/dagger/install.sh | sh
  when: ansible_distribution == "Ubuntu" and check_dagger.rc != 0
  become: yes
  args:
      chdir: "/usr/local"
  tags:
    - dagger
- name: Install dagger macos
  community.general.homebrew:
    name: "dagger/tap/dagger"
    state: latest
  when: ansible_distribution == "MacOSX" and check_dagger.rc != 0
  tags:
    - dagger
