# TODO: pyenv ubuntu
# TODO: tfenv ubuntu
# TODO: pkenv ubuntu
# TODO: fix flips back to system python
# - name: Install pipenv
  # community.general.homebrew:
    # name:  pipenv
    # state: latest
  # when: ansible_distribution == "MacOSX"
  # tags:
    # - devTools
    # - macos
    #
- name: devTools Macos
  community.general.homebrew:
    name: ["pipenv", "pyenv", "tfenv", "pkenv", "tmux", "ripgrep", "docker", "tree", "jq", "luarocks", "fzf"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - devTools
    - macos
- name: devtools Ubuntu
  apt:
    name: ["pipenv", "luarocks", "jq", "tree", "tmux", "docker", "ripgrep", "fzf"]
    state: latest
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags:
    - devTools
    - ubuntu
- name: Install tmux plugin manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    force: yes
  tags:
    - devTools
    - macos
- name: Install luacheck
  become: yes
  shell: |
    luarocks install argparse
    luarocks install luacheck
  tags:
    - devTools
