- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
  tags:
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:teddylear/shell_config.git'
    dest: "{{ lookup('env', 'HOME') }}/shell_config"
    force: yes
    recursive: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: neovim plugin and TS parser update
  ansible.builtin.shell: |
    nvim --headless -c "PackerSync" -c "PackerUpdate" -c "TSUpdateSync" -c "q"
