- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
    - macos
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:teddylear/shell_config.git'
    dest: "{{ lookup('env', 'HOME') }}/shell_config"
    force: yes
    recursive: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
# TODO: Should update this
- name: Setup dotfiles
  ansible.builtin.shell: |
    stow -R alacritty
    stow -R zsh
    stow -R tmux
    stow -R nvim
    source ~/.zshrc
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
- name: neovim plugin and TS parser update
  ansible.builtin.shell: |
    nvim --headless -c "PackerSync" -c "PackerUpdate" -c "TSUpdateSync" -c "q"
