- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
    - macos
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:teddylear/shell_config.git'
    dest: "{{ lookup('env', 'HOME') }}/shell_config"
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Setup dotfiles
  ansible.builtin.shell: |
    omz update
    stow -R zsh
    stow -R tmux
    stow -R nvim
    stow -R alacritty
    source ~/.zshrc
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  tags:
    - dotfiles
- name: Setup i3, compton
  ansible.builtin.shell: |
    stow -R i3
    stow -R compton
    # stow -R polybar
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  when: ansible_distribution == "Ubuntu"
  tags:
    - dotfiles
- name: Clone tree-sitter-cue
  ansible.builtin.git:
    repo: 'git@github.com:eonpatapon/tree-sitter-cue.git'
    dest: "{{ lookup('env', 'HOME') }}/code/tree-sitter-cue"
    force: yes
    update: yes
  tags:
    - dotfiles
    - cue
- name: Make treesitter queries directory for cue
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim/queries/cue"
    state: directory
  tags:
    - dotfiles
    - cue
- name: Copy cue highlight file
  ansible.builtin.shell: "cp {{ lookup('env', 'HOME') }}/code/tree-sitter-cue/queries/highlights.scm ."
  args:
      chdir: "{{ lookup('env', 'HOME') }}/.config/nvim/queries/cue"
  tags:
    - dotfiles
    - cue
