- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
    - macos
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:teddylear/shell_config.git'
    dest: "{{ lookup('env', 'HOME') }}/shell_config"
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Check polybar installed
  ansible.builtin.shell: type polybar
  when: ansible_distribution == "Ubuntu"
  register: check_polybar
  ignore_errors: true
  tags:
    - polybar
- name: Install polybar
  apt:
    name: polybar
    state: present
  when: ansible_distribution == "Ubuntu" and check_polybar.rc != 0
  become: yes
  tags:
    - polybar
- name: Setup polybar stow
  ansible.builtin.shell: |
    stow -R polybar
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  tags:
    - polybar
- name: Setup dotfiles
  ansible.builtin.shell: |
    omz update
    stow -R zsh
    stow -R tmux
    stow -R nvim
    stow -R alacritty
    source ~/.zshrc
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  tags:
    - dotfiles
- name: Setup i3, compton
  ansible.builtin.shell: |
    stow -R i3
    stow -R compton
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  when: ansible_distribution == "Ubuntu"
  tags:
    - dotfiles
