- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
    - macos
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:teddylear/shell_config.git'
    dest: "{{ lookup('env', 'HOME') }}/shell_config"
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
# TODO: Should update this?
- name: Setup dotfiles
  ansible.builtin.shell: |
    stow -R alacritty
    stow -R zsh
    stow -R tmux
    stow -R nvim
    source ~/.zshrc
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  tags:
    - dotfiles
- name: Setup alacritty-macos
  ansible.builtin.shell: |
    stow -R alacritty-macos
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  when: ansible_distribution == "MacOSX"
  tags:
    - dotfiles
- name: Setup i3, compton, alacritty
  ansible.builtin.shell: |
    stow -R alacritty
    stow -R i3
    stow -R compton
  args:
      executable: /bin/zsh
      chdir: "{{ lookup('env', 'HOME') }}/shell_config"
  when: ansible_distribution == "Ubuntu"
  tags:
    - dotfiles
