- name: VLC Media player
  community.general.homebrew_cask:
    name: "vlc"
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - vlc
    - macos
- name: VLC Media player
  apt:
    name: "vlc"
    state: latest
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags:
    - vlc
    - ubuntu
