- name: VLC Media player Macos
  community.general.homebrew_cask:
    name: "vlc"
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - vlc
    - macos
- name: VLC Media player Ubuntu
  apt:
    name: "vlc"
    state: latest
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags:
    - vlc
    - ubuntu
- name: Brave Browser Macos
  community.general.homebrew_cask:
    name: "brave-browser"
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - brave
    - macos
