- name: VLC Media player Macos
  community.general.homebrew_cask:
    name: "vlc"
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - vlc
    - macos
- name: VLC Media player Ubuntu
  apt:
    name: "vlc"
    state: latest
  when: ansible_distribution == "Ubuntu"
  become: yes
  tags:
    - vlc
    - ubuntu
- name: Brave Browser Macos
  community.general.homebrew_cask:
    name: "brave-browser"
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - brave
    - macos
# Prime's brave install
- name: required libraries for brave
  become: true
  apt:
    name: ["curl", "apt-transport-https"]
  tags:
    - brave
    - ubuntu
- name: Brave Browser archive-keyring.gpg download
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - brave
    - ubuntu
- name: Brave Browser PPA setting
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
    - ubuntu
- name: Brave Browser apt installation
  become: true
  apt:
    update_cache: yes
    name: brave-browser
  tags:
    - brave
    - ubuntu
- name: Check okular installed
  ansible.builtin.shell: type okular
  register: check_okular
  ignore_errors: true
  tags:
    - okular
- name: Install okular linux
  become: yes
  apt:
    name: okular
  when: ansible_distribution == "Ubuntu" and check_okular.rc != 0
  tags:
    - okular
