- name: Add Git Config
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: |
      [core]
          pager = delta

      [interactive]
          diffFilter = delta --color-only

      [delta]
          navigate = true  # use n and N to move between diff sections
          line-numbers = true

      [merge]
          conflictstyle = diff3

      [diff]
          colorMoved = default
  tags:
    - gitconfig
