- name: Check golang version
  ansible.builtin.shell: go version | grep {{ go_version }} && echo 'ok'
  register: check_go
  ignore_errors: true
  tags:
    - golang
- name: Confirm $HOME/Downloads directory
  file:
    path: "{{ lookup('env', 'HOME') }}/Downloads"
    state: directory
  tags:
    - golang
- name: Install golang
  become: yes
  ansible.builtin.shell: |
    rm -rf go{{ go_version }}.darwin-amd64.tar.gz
    curl -O -L "https://golang.org/dl/go{{ go_version }}.darwin-amd64.tar.gz"
    rm -rf go
    tar -xf go{{ go_version }}.darwin-amd64.tar.gz
    rm -rf /usr/local/go
    mv -v go /usr/local
  when: check_go.rc != 0
  args:
      chdir: "{{ lookup('env', 'HOME') }}/Downloads"
  tags:
    - golang
- name: Setup go directory
  file:
    path: "{{ lookup('env', 'HOME') }}/go"
    state: directory
  tags:
    - golang
