- name: Check pyright installed
  ansible.builtin.shell: type pyright
  register: check_pyright
  ignore_errors: true
  tags:
    - lsp
    - pyright
- name: Install pyright
  when: check_pyright.rc != 0
  shell: pip install pyright
  tags:
    - lsp
    - pyright
- name: Valid pyright installed
  when: check_pyright.rc != 0
  ansible.builtin.shell: type pyright
  tags:
    - lsp
    - pyright
- name: Check terraform-ls installed
  ansible.builtin.shell: type terraform-ls
  register: check_terraform_ls
  ignore_errors: true
  tags:
    - lsp
    - terraform-ls
- name: Install gpg linux
  when: ansible_distribution == "Ubuntu" and check_terraform_ls.rc != 0
  become: yes
  apt:
    name: gpg
    update_cache: yes
  tags:
    - lsp
    - terraform-ls
- name: setup hashicorp repo
  become: true
  when: ansible_distribution == "Ubuntu" and check_terraform_ls.rc != 0
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  tags:
    - lsp
    - terraform-ls
- name: terraform-ls apt installation
  when: ansible_distribution == "Ubuntu" and check_terraform_ls.rc != 0
  become: true
  apt:
    update_cache: yes
    name: terraform-ls
  tags:
    - lsp
    - terraform-ls
- name: Install terraform-ls macos
  community.general.homebrew:
    name: "hashicorp/tap/terraform-ls"
    state: latest
  when: ansible_distribution == "MacOSX" and check_terraform_ls.rc != 0
  tags:
    - lsp
    - terraform-ls
- name: Valid terraform-ls installed
  when: check_terraform_ls.rc != 0
  ansible.builtin.shell: type terraform-ls
  tags:
    - lsp
    - terraform-ls
- name: Check bashls installed
  ansible.builtin.shell: type bash-language-server
  register: check_bashls
  ignore_errors: true
  tags:
    - lsp
    - bashls
- name: Install bashls
  when: check_bashls.rc != 0
  shell: npm i -g bash-language-server
  tags:
    - lsp
    - bashls
- name: Valid bashls installed
  when: check_bashls.rc != 0
  ansible.builtin.shell: type bash-language-server
  tags:
    - lsp
    - bashls
- name: Check sumneko_lua installed
  ansible.builtin.shell: type lua-language-server
  register: check_sumneko_lua
  ignore_errors: true
  tags:
    - lsp
    - sumneko_lua
- name: Install sumneko_lua
  when: ansible_distribution == "MacOSX" and check_sumneko_lua.rc != 0
  community.general.homebrew:
    name: lua-language-server
    state: latest
  tags:
    - lsp
    - sumneko_lua
# TODO: Add linux install
# Look at primes: https://github.com/ThePrimeagen/ansible/blob/master/tasks/lsp.yml
- name: Valid sumneko_lua installed
  when: check_sumneko_lua.rc != 0
  ansible.builtin.shell: type lua-language-server
  tags:
    - lsp
    - sumneko_lua
