- name: Install neovim build tools ubuntu
  apt:
    name: ["cmake", "gettext", "ninja-build"]
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - neovim
    - ubuntu
- name: Install neovim build tools macos
  community.general.homebrew:
    name: ["ninja"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - neovim
    - macos
- name: Make code directory
  file:
    path: "{{ lookup('env', 'HOME') }}/code"
    state: directory
  tags:
    - neovim
- name: Make local directory for neovim build
  file:
    path: "{{ lookup('env', 'HOME') }}/local"
    state: directory
  tags:
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'git@github.com:neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/code/neovim"
    force: yes
    update: yes
  tags:
    - neovim
- name: neovim clean
  become: yes
  ansible.builtin.shell: make distclean
  args:
      chdir: "{{ lookup('env', 'HOME') }}/code/neovim"
  tags:
    - neovim
- name: neovim build
  become: yes
  ansible.builtin.shell: make CMAKE_BUILD_TYPE=Release install
  args:
      chdir: "{{ lookup('env', 'HOME') }}/code/neovim"
  tags:
    - neovim
- name: setup packer nvim
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - neovim
