- name: Check pyright installed
  ansible.builtin.shell: type pyright
  register: check_pyright
  ignore_errors: true
  tags:
    - python
    - pyright
- name: Install pyright
  when: check_pyright.rc != 0
  shell: |
    pip install pyright
  tags:
    - python
    - pyright
