- name: Check rust version
  ansible.builtin.shell: rustc --version | grep {{ rust_version }} && echo 'ok'
  register: check_rust
  ignore_errors: true
  tags:
    - rust
- name: Install rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y""
  when: check_rust.rc != 0
  args:
      chdir: "{{ lookup('env', 'HOME') }}/Downloads"
  tags:
    - rust
- name: Check cargo-edit version
  ansible.builtin.shell: type cargo-add
  register: check_cargo_edit
  args:
      executable: /bin/zsh
  ignore_errors: true
  tags:
    - cargo-edit
    - rust
- name: Install cargo-edit
  ansible.builtin.shell: cargo install cargo-edit
  when: check_cargo_edit.rc != 0
  args:
      executable: /bin/zsh
  tags:
    - cargo-edit
    - rust
- name: Check stylua version
  ansible.builtin.shell: type stylua
  register: check_stylua
  args:
      executable: /bin/zsh
  ignore_errors: true
  tags:
    - stylua
    - rust
- name: Install stylua
  ansible.builtin.shell: cargo install stylua
  when: check_stylua.rc != 0
  args:
      executable: /bin/zsh
  tags:
    - stylua
    - rust
- name: Check tree-sitter-cli version
  ansible.builtin.shell: type tree-sitter
  register: check_tree_sitter_cli
  args:
      executable: /bin/zsh
  ignore_errors: true
  tags:
    - tree-sitter-cli
    - rust
- name: Install tree-sitter-cli
  ansible.builtin.shell: cargo install tree-sitter-cli
  when: check_tree_sitter_cli.rc != 0
  args:
      executable: /bin/zsh
  tags:
    - tree-sitter-cli
    - rust
- name: Check bat installed
  ansible.builtin.shell: type bat
  register: check_bat
  ignore_errors: true
  args:
      executable: /bin/zsh
  tags:
    - rust
    - bat
- name: Install bat
  ansible.builtin.shell: cargo install --locked bat
  when:  check_bat.rc != 0
  args:
      executable: /bin/zsh
  tags:
    - rust
    - bat
- name: Check sd installed
  ansible.builtin.shell: type sd
  register: check_sd
  ignore_errors: true
  tags:
    - rust
    - sd
- name: Install sd
  ansible.builtin.shell: cargo install sd
  when: check_sd.rc != 0
  tags:
    - rust
    - sd
- name: Check procs installed
  ansible.builtin.shell: type procs
  register: check_procs
  ignore_errors: true
  tags:
    - rust
    - procs
- name: Install procs
  ansible.builtin.shell: cargo install procs
  when: check_procs.rc != 0
  tags:
    - rust
    - procs
- name: Check delta installed
  ansible.builtin.shell: type delta
  register: check_delta
  ignore_errors: true
  tags:
    - rust
    - delta
- name: Install delta
  ansible.builtin.shell: cargo install git-delta
  when: check_delta.rc != 0
  tags:
    - rust
    - delta
- name: Check mprocs installed
  ansible.builtin.shell: type mprocs
  register: check_mprocs
  ignore_errors: true
  tags:
    - rust
    - mprocs
- name: Install mprocs
  ansible.builtin.shell: cargo install mprocs
  when:  check_mprocs.rc != 0
  tags:
    - rust
    - mprocs
