- name: Check rust version
  ansible.builtin.shell: rustc --version | grep {{ rust_version }} && echo 'ok'
  register: check_rust
  ignore_errors: true
  tags:
    - rust
- name: Install rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y""
  when: check_rust.rc != 0
  args:
      chdir: "{{ lookup('env', 'HOME') }}/Downloads"
  tags:
    - rust
