# TODO: How to automate font on ubuntu
- name: Tap nerd fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install fonts
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: upgraded
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install alacritty apt repository
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
- name: Install alacritty
  apt:
    name: alacritty
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
# TODO: Make this only do this if zsh not the default
# - name: Set zsh as default if not using zsh currently
  # shell: chsh -s $(which zsh)
  # tags:
    # - terminal
- name: oh-my-zsh
  ansible.builtin.git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: "{{ lookup('env', 'HOME') }}/oh-my-zsh"
    force: yes
    accept_hostkey: yes
  tags:
    - terminal
- name: oh-my-zsh spaceship
  community.general.homebrew:
    name: spaceship
    state: upgraded
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install zsh-syntax-highlighting
  community.general.homebrew:
    name: zsh-syntax-highlighting
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install zsh-autosuggestions
  community.general.homebrew:
    name: zsh-autosuggestions
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
