- name: Install zsh
  become: yes
  apt:
    name: zsh
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - zsh
- name: zsh path
  shell: which zsh
  register: zsh_path
  tags:
    - terminal
    - zsh
- name: Change shell to zsh
  become: yes
  shell: chsh -s {{ zsh_path.stdout }}
  tags:
    - terminal
    - zsh
- name: Downloads directory
  file:
    path: "{{ lookup('env', 'HOME') }}/Downloads"
    state: directory
  tags:
    - terminal
    - fonts
- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
    - fonts
- name: Install fontconfig
  become: yes
  apt:
    name: fontconfig
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
    - fonts
- name: Check for Hack fonts Ubuntu
  ansible.builtin.shell: fc-list | grep "Hack"
  register: check_hack_fonts
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true
  tags:
    - terminal
    - fonts
- name: Install Hack Nerd font
  become: yes
  ansible.builtin.shell: |
    # https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack#quick-installation
    # Download zip
    curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    # Unzip to location
    unzip Hack.zip -d /usr/share/fonts
    # Clear and regen font cache
    fc-cache -f -v
  when: ansible_distribution == "Ubuntu" and check_hack_fonts.rc != 0
  args:
      chdir: "/tmp"
  tags:
    - terminal
    - fonts
- name: Verify nerd fonts install ubuntu
  ansible.builtin.shell: fc-list | grep "Hack"
  when: ansible_distribution == "Ubuntu" and check_hack_fonts.rc != 0
  tags:
    - terminal
    - fonts
- name: Tap nerd fonts MacOS
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
    - fonts
- name: Install fonts
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: present
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
    - fonts
- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: upgraded
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
- name: Install alacritty apt repository
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
- name: Install alacritty
  apt:
    name: alacritty
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
# TODO: Make this only do this if zsh not the default
# - name: Set zsh as default if not using zsh currently
  # shell: chsh -s $(which zsh)
  # tags:
    # - terminal
# - name: oh-my-zsh
  # ansible.builtin.git:
    # repo: 'https://github.com/robbyrussell/oh-my-zsh'
    # dest: "{{ lookup('env', 'HOME') }}/oh-my-zsh"
    # force: yes
    # accept_hostkey: yes
  # tags:
    # - terminal
    # - zsh
- name: oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - terminal
    - zsh
- name: Check zsh spaceship installed
  stat:
      path: ~/.oh-my-zsh/custom/plugins/spaceship
  register: check_spaceship
  tags:
    - terminal
    - zsh
- name: Install zsh spaceship
  ansible.builtin.shell: |
    git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
  when: not check_spaceship.stat.exists
  tags:
    - terminal
    - evalcache
    - zsh
- name: Install Terminal stuff ubuntu
  become: yes
  apt:
    name: ["zsh-autosuggestions", "zsh-syntax-highlighting"]
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - ubuntu
    - zsh
- name: Install Terminal stuff macos
  community.general.homebrew:
    name: ["spaceship", "zsh-autosuggestions", "zsh-syntax-highlighting"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - terminal
    - macos
    - zsh
- name: Check for neofetch Installation
  shell: which neofetch
  register: neofetch_installed
  ignore_errors: yes
  tags:
    - terminal
    - neofetch
- name: Install neofetch macos
  community.general.homebrew:
    name: "neofetch"
    state: latest
  when: ansible_distribution == "MacOSX" and neofetch_installed is failed
  tags:
    - terminal
    - neofetch
    - macos
- name: Install neofetch Ubuntu
  become: yes
  apt:
    name: "neofetch"
    state: latest
  when: ansible_distribution == "Ubuntu" and neofetch_installed is failed
  tags:
    - terminal
    - neofetch
    - ubuntu
- name: Check for Mcfly Installation
  shell: which mcfly
  register: mcfly_installed
  ignore_errors: yes
  tags:
    - terminal
    - mcfly
- name: Tap Mcfly macos
  community.general.homebrew_tap:
    name: cantino/mcfly
    state: present
  when: ansible_distribution == "MacOSX" and mcfly_installed is failed
  tags:
    - terminal
    - mcfly
    - macos
- name: Install Mcfly macos
  community.general.homebrew:
    name: "mcfly"
    state: latest
  when: ansible_distribution == "MacOSX" and mcfly_installed is failed
  tags:
    - terminal
    - mcfly
    - macos
- name: Install Mcfly Ubuntu
  shell: curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly
  become: yes
  when: ansible_distribution == "Ubuntu" and mcfly_installed is failed
  tags:
    - terminal
    - mcfly
    - ubuntu
- name: Check exa installed
  ansible.builtin.shell: type exa
  register: check_exa
  ignore_errors: true
  tags:
    - terminal
    - exa
- name: Install exa linux
  become: yes
  # TODO: How to make this grab latest?
  ansible.builtin.shell: |
    wget -c http://old-releases.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
    apt-get install ./exa_0.9.0-4_amd64.deb
  args:
      chdir: "{{ lookup('env', 'HOME') }}/Downloads"
  when: ansible_distribution == "Ubuntu" and check_exa.rc != 0
  tags:
    - terminal
    - exa
- name: Install exa macos
  community.general.homebrew:
    name: "exa"
    state: latest
  when: ansible_distribution == "MacOSX" and check_exa.rc != 0
  tags:
    - terminal
    - exa
- name: Confirm $HOME/.local/bin directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - fd
- name: Check fd installed
  ansible.builtin.shell: type fd
  register: check_fd
  ignore_errors: true
  tags:
    - terminal
    - fd
- name: Install fd linux
  become: yes
  ansible.builtin.shell: apt install fd-find
  when: ansible_distribution == "Ubuntu" and check_fd.rc != 0
  tags:
    - terminal
    - fd
- name: Linux fd Ubuntu
  ansible.builtin.shell: ln -s $(which fdfind) ~/.local/bin/fd
  when: ansible_distribution == "Ubuntu" and check_fd.rc != 0
  tags:
    - terminal
    - fd
- name: Install fd macos
  community.general.homebrew:
    name: "fd"
    state: latest
  when: ansible_distribution == "MacOSX" and check_fd.rc != 0
  tags:
    - terminal
    - fd
- name: Check zsh evalcache installed
  stat:
      path: ~/.oh-my-zsh/custom/plugins/evalcache
  register: check_evalcache
  tags:
    - terminal
    - evalcache
    - zsh
- name: Install zsh evalcache
  ansible.builtin.shell: git clone https://github.com/mroth/evalcache ~/.oh-my-zsh/custom/plugins/evalcache
  when: not check_evalcache.stat.exists
  tags:
    - terminal
    - evalcache
    - zsh

