- name: Tap nerd fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present
  tags:
    - terminal
- name: Install fonts
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: present
  tags:
    - terminal
- name: Install alacritty
  community.general.homebrew_cask:
    name: alacritty
    state: upgraded
  tags:
    - terminal
- name: Set zsh as default if not using zsh currently
  shell: chsh -s $(which zsh)
  tags:
    - terminal
