- name: Install window management
  community.general.homebrew_cask:
    name: ["amethyst", "caffeine"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - window_management
    - macos
# Prime's ubuntu ansible stuff
- name: Install desktop stuff
  become: true
  apt:
    name: [ "compton",  "i3", "dconf-editor", "moreutils", "ubuntu-mate-desktop" ]
  when: ansible_distribution == "Ubuntu"
  tags:
    - window_management
    - ubuntu
- name: dconf i3 window manager
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - window_management
    - ubuntu
- name: dconf i3 show-desktop-icons false
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - window_management
    - ubuntu
- name: Add i3-gaps apt-repo
  become: yes
  ansible.builtin.apt_repository:
    repo: 'ppa:regolith-linux/release'
    state: present
  tags:
    - window_management
    - ubuntu
    - i3-gaps
- name: Install desktop stuff
  become: yes
  apt:
    name: "i3-gaps"
    update_cache: yes
    state: latest
  when: ansible_distribution == "Ubuntu"
  tags:
    - window_management
    - ubuntu
    - i3-gaps
- name: Check polybar installed
  ansible.builtin.shell: type polybar
  become: yes
  register: check_polybar
  ignore_errors: true
  when: ansible_distribution == "Ubuntu"
  tags:
    - window_management
    - ubuntu
    - polybar
- name: Install polybar
  become: yes
  when: check_polybar.rc != 0
  when: ansible_distribution == "Ubuntu"
  apt:
    name: "polybar"
    update_cache: yes
    state: latest
  tags:
    - window_management
    - ubuntu
    - polybar
