- name: Install window management
  community.general.homebrew_cask:
    name: ["amethyst", "caffeine"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - window_management
    - macos
# TODO:Setup i3 installation
