- name: Install window management
  community.general.homebrew_cask:
    name: ["amethyst", "caffeine"]
    state: latest
  when: ansible_distribution == "MacOSX"
  tags:
    - window_management
    - macos
# Prime's ubuntu ansible stuff
- name: Install desktop stuff
  become: true
  apt:
    name: [ "compton",  "i3", "dconf-editor", "moreutils", "ubuntu-mate-desktop" ]
  when: ansible_distribution == "Ubuntu"
  tags:
    - window_management
    - ubuntu
- name: dconf i3 window manager
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - window_management
    - ubuntu
- name: dconf i3 show-desktop-icons false
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - window_management
    - ubuntu
